### ISSUE TITLE
9주차 스터디

### ISSUE THREAD

**Issue by JSYoo5B** [morebo2ks/Designing_Data_Intensive_Application#10]
## 파트

6. 파티셔닝: 보조 색인 이후

## 발표자

* 김재훈

## 발표 기간

* 5월 17일 오후 10시

## 마감기한

* 5월 17일 오후 9시 59분

## 참고 링크

* 일정표 :  https://clever-bull-d00.notion.site/bd201441d8a44c83a70375001278c850
* 책 : http://www.yes24.com/Product/Goods/59566585

**Comment by JSYoo5B** [comment]
## 파티션 재균형화

진정한 재균형화 사유는 "현재 파티션이 다루는 데이터 범위 내 양이 너무 많아지는 경우"라고 생각한다.
책에서 언급한 이유도 가능한 사유지만, 대부분은 파티션의 복제를 늘리거나 고가용성 측면이라 생각한다.

어떤 원인으로 재균형화가 일어나던, 책에서 언급한 최소 요구사항은 모두 적용된다.

* 재균형화 후 부하가 노드들에게 동일하게 한다.  
  (현실적으로 불가능하지만 이상향으로 잡는다.)  
  (굳이 비유자면 P50과 P99의 격차를 줄인다.)
* 재균형화 도중에 읽기/쓰기가 가능해야 한다.
* 재균형화는 빨리 실행되어야 한다.  
  불필요한 디스크, 네트워크 IO가 발생해선 안된다.

### 재균형화 전략

이전 키를 기반으로 한 해싱 전략에서, 해시 값을 N빵하는 전략은 쓰면 안된다.
노드가 늘어나면 N += 1이 되며, 그러면 기존 데이터들이 다른 노드로 재배치 될 수 있다.

1. 파티션 개수 고정

진작에 파티션 개수를 노드보다 심하게 많은 개수로 고정해놓고 시작한다.
(노드가 10개인데 파티션이 100개, 균등 배포시 각 노드가 레플리카 없이 100개 파티션을 받도록 한다.)
노드가 추가되면, 각 노드에서 몇개 파티션을 뺏어오는 방식으로 노드 당 파티션 균형을 맞춘다.
(1000개 파티션의 노드가 10개에서 11개가 되면 1000/11인 평균 91개의 파티션을 갖게 한다.)
기존 파티션 데이터는 변경되지 않으며, 단지 파티션을 들고 있는 노드 정보가 변경되는 것이다.

전체 데이터셋의 크기가 크게 변동되지 않을 상황에 적합함. (적절한 파티션 개수를 지정할 수 있음)

2. 동적 파티셔닝

파티션의 크기가 넘어가면 동적으로 파티셔닝을 실행 (초반에 내가 생각한 원인)
파티셔닝을 수동으로 하면 파티션의 크기가 불균형해질 때마다 직접 파티션을 변경해야 함.
B트리와 같은 방식으로 데이터의 삽입/삭제에 따라 파티션이 분리되거나 축소된다.

다만 이렇게 동적으로 할 경우, 데이터가 적을 경우 파티션이 하나가 된다는 단점이 있다고 한다.
(무슨 상관인지 모르겠다. 데이터의 크기가 작아서 순수 복제가 가능한 상황인데)

3. 노드 비례 파티셔닝

지금까지는 파티션의 개수를 고정하거나, 각 파티션의 최대 크기를 고정했다.
이번에는 각 노드별로 가질 수 있는 파티션의 최대 개수를 설정한다.

### 운영과 재균형화

데이터베이스를 운영할 때, 재균형화는 수동으로 해야할까? 자동으로 해야할까?
재균형화 방식을 제안하고 관리자가 재균형화 여부를 결정해야 반영되는 반반 전략도 존재한다.

완전 자동화의 경우 일상적 유지보수에는 손이 덜 가는 당점이 있으나, 예측이 어려울 수 있다.
재균형화가 수행될 때는 무거운 네트워크, 디스크 IO가 발생하는데, 자동화의 경우 예측 못하게 된다.

## 요청 라우팅

지금까지는 데이터를 어떤 방식으로 파티셔닝하고, 어떻게 인덱싱을 할지 결정했다.
이제 클라이언트가 원하는 데이터를 접근하려면 어떻게 요청이 라우팅되어야 할지 알아본다.

1. 클라이언트는 특정 노드에게 데이터를 요청한다.  
   당연히 부하 분산을 고려하여 노드는 서로 분산되어 호출된다 가정한다.  
   요청 받은 노드에 해당 데이터가 있다면 다행이지만, 없다면 그 노드를 찾아야 한다.
2. 클라이언트의 요청은 라우팅 계층으로 보내서, 요청 데이터에 대한 노드를 찾아야 한다.  
   이 때 라우팅 계층은 노드의 위치만 알려줄 뿐, 요청을 실제 처리하진 않는다.
3. 실제 데이터를 가진 노드에게 클라이언트가 요청을 날리게 된다.

## 병렬 질의 실행

10장으로 미룸

**Comment by hyunju-song** [comment]
## 파티션 재균형화

- 데이터베이스의 변화로 데이터와 요청이 한 노드에서 다른 노드로 옮겨져야 한다. 이를 재균형화라 한다
- 최소 요구사항
    - 부하가 노드들 사이에 균등하게 분배
    - 재균형화 도중에도 읽기쓰기 요청을 받아들여야 함

## 재균형화 전략

### 쓰면 안되는 방법: 해시값에 모드 N연산을 실행

- hash mod 10은 0과9 사이의 숫자를 반환한다
- 이의 문제는 노드개수 n이 바뀌면 대부분의 키가 노드 사이에 옮겨져야 한다는 점이다
- 가령 hash = 1234546 일때 처음에 노드가 10대라면 이 키는 노드 6에 할당된다. 노드가 11대로 늘어나면 이 키는 노드 3으로 옮겨져야 하고 노드가 12대로 늘어나면 노드 0으로 옮겨져야 한다.
- 이렇게 키가 자주 이동하면 재균형화 비용이 지나치게 커진다.

### 파티션 개수 고정

- 파티션을 노드 대수보다 많이 만들고 각 노드에 여러 파티션을 할당하는 것이다.
- 클러스터에 노드가 추가되면 새 노드는 파티션이 다시 균일하게 분배될때까지 기존 노드에서 파티션 몇 개를 뺏어올 수 있다.
- 파티션은 노드 사이에서 통째로 이동하기만 하면 된다
- 유일한 변화는 노드에 어떤 파티션이 할당되는가 뿐이다
- 보통 데이터베이스가 처음 구축될때 파티션 개수가 고정되고 이후에 변하지 않는다.
- 보통 이러면 파티션 분할을 지원하지 않는다.
- 처음 설정한 개수가 사용가능한 노드 대수의 최대치가 되므로 미래에 증가될 것을 수용하기에 충분히 높은 값으로 선택해야한다.
- 그러나 개별 파티션도 관리 오버헤드가 있으므로 너무 큰수를 선택하면 역효과를 낳을 수 있다.

### 동적 파티셔닝

- 키 범위 파티셔닝을 사용하면 고정 파티셔닝이 매우 불편하다
    - 경계를 잘못 지정하면 모든 데이터가 한 파티션에 저장되고 나머지 파티션은 텅 빌 수도 있다
- 파티션은 노드 하나에 할당되고 각 노드는 여러 파티션을 담당할 수 있다.
- 큰 파티션이 쪼개진 후 부하의 균형을 맞추기 위해 분할된 파티션 중 하나가 다른 노드로 이동될 수 있다.
- 파티션 크기가 설정된 값을 넘어서면 파티션을 두개로 쪼개고, 많이 삭제되면 인접한 파티션과 합쳐질 수 있다.
- 파티션 개수가 전체 데이터 용량에 맞춰 조정된다는 이점이 있다.
- 초기 데이터베이스는 파티션 경계를 위한 사전 정보가 없으므로 시작할때는 파티션이 하나라는 함정이 있다.
    - 초기 파티션 집합을 설정할 수 잇게 사전분할을 한다.
- 해시 파티셔닝에도 똑같이 사용될 수 있다.

### 노드비례 파티셔닝

- 동적 파티셔닝은 파티션 개수가 데이터셋 크기에 비례한다.
- 노드비례 파티셔닝은 노드당 할당되는 파티션 개수를 고정한다.
- 노드 대수가 변함없는 동안은 개별 파티션 크기가 데이터셋 크기에 비례해서 증가하지만 노드 대수를 늘리면 파티션 크기는 다시 작아진다.
- 파티션 경계를 무작위로 선택하려면 해시기반 파티셔닝을 사용해야한다.

## 운영: 자동 재균형화와 수동 재균형화

- 완전 자동 재균형화 : 관리자의 개입이 전혀 없이 시스템이 자동으로 언제 파티션을 노드 사이에 이동할지 결정함
    - 유지보수에 손이 덜가고 편리함
    - 예측하기 어려움
    - 자동장애감지와 조합하면 위험해진다
- 완전 수동 재균형화 : 관리자가 명시적으로 파티션을 노드에 할당하도록 설정하고 관리자가 재설정할때만 파티션 할당이 변경됨

## 요청 라우팅

- 클라이언트에서 요청을 보내려고 할때 어느 노드로 접속해야하는지 어떻게알 수 있을까?
- 접근법
    - 클라이언트가 아무 노드에나 접속하게 한다
    - 모든 요청을 라우팅 계층으로 먼저 보낸다
    - 파티셔닝 방법과 파티션이 어떤 노드에 할당됐는지를 알고 있게 한다
- 분산 데이터 시스템은 클러스터 메타데이터를 추적하기위해 주키퍼 같은 별도의 코디네이션 서비스를 사용한다.

### 병렬질의 실행

- 복잡한 질의를 여러 실행단계와 파티션으로 분해하며 이들 중 다수는 데이터베이스 클러스터 내의 서로 다른 노드에서 병렬적으로 실행될 수 있다.

## 정리

- 목적은 핫스팟이 생기지 않게 하면서 데이터와 질의 부하를 여러 장비에 균일하게 분배하는 것이다.
- 파티셔닝 방법
    - 키범위
    - 해시
- 보조색인
    - 문서 파티셔닝 색인(지역색인)
    - 용어 파티셔닝 색인(전역색인)

**Comment by jasonkang14** [comment]
# Rebalancing Partitions
load를 하나의 노드에서 다른 노드로 옮기는 것을 리밸런싱이라고 함. 
파티션 리밸런싱이 필요한 경우는
- query throughput 증가
- 데이터셋 사이즈 증가
- machine failure 

## Strategies for Rebalancing
### How not to do it: hash mod N
- 값을 균일하게 나눌 수 있을 것 같지만, rebalancing할 때 너무 많은 이동이 발생해서 비용증가
- 데이터를 `적당히` 옮길 수 있는 방법이 필요함

### Fixed number of partitions
- 전체 파티션의 수를 고정시키는 것
- 만약 노드가 추가된다면 load가 균일해질 때까지 기존 노드들로부터 파티션을 나눠받음
- 파티션 수는 변하지 않고, 파티션이 어떤 노드에 배정되었는지만 변경됨
- 파티션 수가 고정되어있기 때문에, 데이터 양이 증가하면 각 파티션의 크기도 증가하게 됨
- 따라서 `적당한` 파티션 수를 정해야함

### Dynamic partitioning
- 실시간(?) 으로 파티셔닝 하는 것
- range partition의 경우 특정 파티션에서 hot spot이 발생할 수 있기 때문에 load를 수시로 분산시켜줘야함

### Partitioning proportionally to nodes
- 위의 2가지 방식은 데이터가 늘어남에 따라 파티션을 하기 때문에 노드수와 파티션의 수가 서로 관련없음
- 각 노드별 파티션을 몇 개 가질 수 있는지를 정하는 방식
- 노드가 추가되면 랜덤하게 기존 파티션들을 쪼개서 노드별 파티션 수를 유지함

## Operations: Automatic or Manual Rebalancing
- 완전 자동화는 operation 측면에서 편리하긴 한데, 예측할 수 없다는 문제가 있음
- 만약 네트워크 문제로 단순히 오래걸리는건데 죽었다고 판단해서 REBALANCING을 한다면 비용이 상당함
- 죽었다는 것의 기준을 정하는게 분산 시스템에서 중요한듯
- 따라서 왠만하면 manual하게 처리하는 것이 좋다

# Request Routing
- client가 어떤 Node에 요청을 보낼지 결정하는 방법 대표적으로 3가지 방법이 있다
1. client는 아무 node에 요청을 보내고, 해당 node가 redirect 등을 통해 request를 어떻게 처리할지 결정함
2. client는 지정된 node에 요청을 보내고, 해당 node가 redirect 등을 통해 request를 어떻게 처리할지 결정함
3. client가 node의 partition정보를 가지고 있고, redirect 없이 해당 node를 통해 request를 처리함

- 상당수의 분산시스템이 ZooKeeper같은 별도의 코디네이션 서비스를 사용함
- MongoDB도 ZooKeeper는 아니지만 유사하게 config server를 사용
- Cassandra는 아무 node에다 요청을 보내면 서로 요청을 전달하면서 처리함 (gossip)

## Parallel Query Execution
- 데이터 분석의 경우에는 대용량 쿼리를 병렬로 처리해야 할 수 있음

**Comment by KilJaeeun** [comment]
### 파티셔닝과 보조색인
- 보조색인 : 보통레코드를 유일하게 식별하는 용도가 아닌 특정 값이 발생한 항목 검색 수간
- 솔라, 엘라스틱서치 같은 검색 서버에 존재의 이유
- 문서 기반 파티셔닝(지역 색인)과 용어 기반 파티셔닝 (전역 색인)이 존재
   - 문서기반 파티셔닝
       -  모든 파티션에 질의를 보내는 스캐터, 개더 존재
       - 읽기 연산 > 쓰기연산
       - 몽고DB, 리악, 카산드라, 엘라스틱서치, 솔라 클라우드, 볼트 DB
    -  용어기반 파티셔닝 
      -  쓰기연산 > 읽기 연산
      -  용어 자체 로 가면  범위 스캔 용이 vs 해시로 가면 부하가 고르게 분산
      - 비동기 보조색인 갱신(모든 DB에서 분산 트랜잭션 지원안함)

# 파티션 재균형화 
- 한 노드에서 다른 노드로 부하를 옮기는 과정을 의미
- 최소 요구사항
  -  부하 균등 배포
  - 재균형 도중에 읽기, 쓰기 요청 받음
  - 재균형화가 빨리 실행되고 네트워크 와 디스크io 의 부하 최소화를 위해 데이터가 필요 이상 옮겨지면 안됨
## 재균형화 전략
- mod 로 n 수행하면, 나중에 n 이 바뀌면 대규모 공사가 발생하니, 필요 이상으로 옮기지 않는 전략을 이용해라
- 파티션 개수 고정 : 1000개의 파티션 으로 쪼개 각 노드마다 100개 파티션 할당. 노드 추가시, 일부 파티션을 넣는다. 이론상 클러스터 성능다른 hw 고려 또한 가능.  리악, 엘라스틱 서치, 카우치베이스, 볼드모트. 이론상 파티션 개수가 영영 고정이고 일부 DB에서는 아예 못바꾸에 고정. 그러나, 개별 파티션 관리 오버헤드가 있어 너무 큰 수 선택시 역효과. 딱 적당한 수 찾기가 은근 어렵다.
- 동적 파티셔닝 : 비트리마냥, 파티션 크기가 설정된 값 넘어가면  파티션 분할돼 원래 파티션의 절반정도의 데이터가 포함되게됨. hbase, 리싱크 Db, 키범위 파티셔닝을 사용하는 데이터베이스에서 동적 파티션 이용, 파티션 개수가 전체 데이터 용량에 맞춰 조정되는 이점. 그러나 시작 파티션 사전 분할 개수를 지정하지 않으면 파티션 1. 동적 파티셔닝은 키범위 파티셔닝 뿐만 아니라 해시 파티셔닝도 같이 이용 가능(예. 몽고db)
- 노드비례 파티셔닝
 -  파티션 개수와 노드 대수 비례. 노드당 할당되는 파티션 개수 고정, 개별 파티션 크기 상당히 안정적 유지됨. 재균형 알고리즘 o. 해시기반 파티셔닝 이용


## 운영  : 자동 재균형화와 수동 재균형화
- 과부화 걸려 연쇄로 울 수 있으니 수동이 도움됨

# 요청 라우팅
- 서비스 찾기 문제
1. 아무 노드에 접근해서 물어 간다. (가십 프로토콜)
2. 라우팅 계층이 존재해 (주키퍼의 도움을 받거나, 대체제거나) 물어 간다.
3. 클라이언트가 사전에  해당 파티션 노드 위치를 알 수 있다.

**Comment by wookiist** [comment]
# 파티션 재균형화
- 새로운 노드를 추가하거나 제거하는 경우처럼, 클러스터에서 한 노드가 담당하던 부하를 다른 노드로 옮기는 과정
- 방식과 무관하게 만족해야 하는 최소 요구사항
  - 재균형화 후, 부하가 클러스터 내에 노드 사이에서 균등 분배될 것
  - RW 요청은 허용되어야 한다.
  - 필요이상의 (최소한만) 데이터가 옮겨지도록 할 것
## 재균형화 전략
### 해시값에 MOD N 연산 수행 (쓰지 말 것)
- 노드 개수가 바뀌면, 대부분의 키가 노드 사이에 옮겨져야 한다는 점이 문제
- 데이터를 필요 이상으로 움직이기 때문에 권장하지 않음
### 파티션 개수 고정
- 파티션수를 노드 대수보다 많이 만들고, 각 노드에 여러 파티션을 할당하는 방식
  - 예를 들어 노드 10대로 구성된 클러스터에선, 처음부터 파티션을 1,000개로 쪼개서 각 노드마다 약 100개의 파티션을 할당 가능
- 파티션의 개수는 바뀌지 않고 키도 변경되지 않는다. 
- 데이터 전송 중에 읽기 쓰기가 발생하면, 기존 파티션을 활용
- 성능이 좋은 노드가 섞여 있으면, 해당 노드에 좀 더 배치하도록 설정할 수도 있음
- 다만, 처음 설정된 파티션 개수가 앞으로 사용 가능한 노드 대수의 최대치가 되므로, 미래 증가분까지도 예측하고 충분히 높은 값으로 세팅하는 것이 좋음 
### 동적 파티셔닝
- HBase처럼 키 범위 파티셔닝을 사용하는 경우, 파티션을 동적으로 만듦 (파티션 경계를 수동 설정하면 매우 성가시고, 잘못될 위험성도 커서)
- 각 파티션은 노드 하나에 할당되고, 각 노드는 여러 파티션을 담당할 수 있음 
- 동적 파티셔닝은 파티션 개수가 전체 데이터 용량에 맞춰 조정 됨
- 그러나 빈 DB의 경우엔 파티션 경계를 정할 수 있는 사전 정보가 없으니, 문제가 됨. 그래서 HBase에선 Pre-Splitting을 함 
### 노드 비례 파티셔닝
- 카산드라 등에서 사용되는 방법으로 파티션 개수가 노드 대수에 비례하게 설정
- 일반적으로 데이터 용량이 클수록 데이터 저장에 필요한 노드도 많아져서, 이 방법을 쓰면 개별 파티션 크기도 상당히 안정적이 됨 
### 운영: 자동 재균형화와 수동 재균형화
- 완전 자동 재균형화는 손이 덜 가니 편하지만, 예측이 어려움
- 자동화가 위험한 점은, 장애 감지가 오작동하는 경우. 노드 한 대에 과부하가 걸려 일시적으로 요청에 대한 응답이 느려진다고 할 때, 노드가 죽은 상태라고 오해할 수 있음 -> replication storm~!
# 요청 라우팅
- 클라이언트에서 요청을 보내려 할 때, 어느 노드로 접속해야 하는지 어떻게 알 수 있나? 
- 서비스 찾기의 일종.
  1. 클라이언트가 아무 노드에나 접속하게 하기 
  2. 클라이언트의 모든 요청을 라우팅 계층에 일단 전달 (라우팅 계층은 그저 partition-aware lb로 동작)
  3. 클라이언트가 파티셔닝 방법과 파티션이 어떤 노드에 할당됐는지 알게 함. (알잘딱해라)
## 병렬 질의 실행
- MPP (Massively Parallel Processing) 제품은 더 복잡한 종류의 질의를 지원

**Comment by dns02023** [comment]
금일 발표자료: https://quill-clutch-d78.notion.site/6-863ddbebb2b141978f06f571557f912c
